apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: workload-dev
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: 'https://kubernetes.default.svc'
  project: dev
  source:
    repoURL: 'wkshpflqsk.azurecr.io'
    chart: aci-hello
    targetRevision: 0.1.1
    helm:
      values: |
        image:
          repository: wkshpflqsk.azurecr.io/aci-hello
          tag: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
